development:
  stripe_secret_key: 'sk_test_51L2tJMHRTN8RwwVxSAEbuzhIaT3ooXmgaVzVbNaNMU3FXVXsjJZGUCqjLEq41M6mfc9UR9cufUjy8BUOS7JI27Zu00KvSTwakJ'
  stripe_publishable_key: 'pk_test_51L2tJMHRTN8RwwVxmZ0NNwGprrfisF6kY1HFnCEwlno7ARt9eINbGCX4AdMFIKwjOGGULdqqg72jWlgEcToVD2XZ00IWYVhNvR'
